### ISSUE TITLE
eslint-plugin-mediawiki/src/utils.js fails on null types in json file

### ISSUE THREAD

**Issue by umherirrender** [wikimedia/eslint-plugin-mediawiki#59]
The upgrade of eslint-config-wikimedia from 0.17.0 -> 0.18.1 is broken for mediawiki/extensions/TEI

Log: https://libraryupgrader2.wmcloud.org/logs2/84600

The error is:
```
TypeError: Cannot read property 'type' of null
Occurred while linting /src/repo/data/mw_tei_json_definition.json:1
    at Object.requiresCommentList (/src/repo/node_modules/eslint-plugin-mediawiki/src/utils.js:67:17)
    at ObjectExpression (/src/repo/node_modules/eslint-plugin-mediawiki/src/rules/class-doc.js:41:16)
    at listeners.(anonymous function).forEach.listener (/src/repo/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/src/repo/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/src/repo/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/src/repo/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/src/repo/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/src/repo/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at nodeQueue.forEach.traversalInfo (/src/repo/node_modules/eslint/lib/linter/linter.js:952:32)
```

The file in question is https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/TEI/+/refs/heads/master/data/mw_tei_json_definition.json#33
it contains the json value `null`, which looks like a possible problem here, but not sure.

Please have a look. Thanks

**Comment by catrope** [comment]
This is strange, the stack trace indicates that the `class-doc` rule (which is intended for JavaScript) is being applied in a JSON file.

**Comment by umherirrender** [comment]
If the key "classes" in the root gets renamed, it works.
```
{
	"classes": {  <!-- rename this key and it works
....
	},
	"start": [
		"text"
	]
}
```
